apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# HIGHLIGHT
- https://github.com/aws-samples/eks-workshop-v2/tree/stable/manifests/base-application/ui
patches:
# HIGHLIGHT
- path: deployment-patch.yaml
